name: Jpackage Linux

on:
  workflow_dispatch:

jobs:
  build-gradle-project-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.3'

      - name: Install fakeroot
        run: sudo apt-get update && sudo apt-get install fakeroot -y

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run customFatJar task
        run: ./gradlew customFatJar

      - name: Check jpackage availability
        run: jpackage --input build/libs/ --name CargoManager --main-jar CargoManagerJAR-1.0-SNAPSHOT.jar --main-class com.heshanthenura.shipcargomanager.Launcher --type deb --dest build/linux/ --app-version 1.0 --vendor "Heshan Thenura" --icon icon/icon.png --linux-shortcut

      - name: List contents of build/linux directory
        run: ls -l build/linux

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CargoManager-linux
          path: build/linux/*

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: linux-v1.0
          release_name: CargoManager-linux
          draft: false
          prerelease: false

      - name: Upload artifact to release
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux/cargomanager_1.0-1_amd64.deb
          asset_name: CargoManager-linux.deb
          asset_content_type: application/octet-stream